### ISSUE TITLE
New version BetterDiscord

### ISSUE THREAD

**Issue by Serega007RU** [Strencher/BdBrowser#17]
A new version of BetterDiscord has been released, please update

**Comment by Serega007RU** [comment]
Hey! Maybe issue should be closed only when the issue is really resolved? The problem is still relevant!

**Comment by dav1312** [comment]
😞 
![image](https://user-images.githubusercontent.com/63931154/151146296-5f5a1baa-3396-498d-8364-59e733ae1b0c.png)

**Comment by Serega007RU** [comment]
Well, this is very sad, but the browser works much more optimized than discord
