### ISSUE TITLE
How do I install BDBrowser

### ISSUE THREAD

**Issue by AHIRAISSHY** [Strencher/BdBrowser#2]
doing this for testing purposes

**Comment by LweoIsHere** [comment]
what if i have opera gx?

**Comment by Flam3rboy** [comment]
I would suggest making a Readme for a better overview.

**Comment by Strencher** [comment]
> I would suggest making a Readme for a better overview.
I added a readme a few days ago.

**Comment by Strencher** [comment]
I'm going to close this since we have a readme now.
