### ISSUE TITLE
for firefox???

### ISSUE THREAD

**Issue by schelef** [Strencher/BdBrowser#26]
why only chromium?

**Comment by schelef** [comment]
ok

**Comment by RadNotRed** [comment]
Reversitized google chromium ungoogled hacker firefox master gamer pro

**Comment by schelef** [comment]
@RadNotRed nigga penis

**Comment by RadNotRed** [comment]
WHAT THE FUCK

**Comment by RadNotRed** [comment]
Imagine not being able to use this on firefox
LOL
