### ISSUE TITLE
Accidentally turned on 2 themes that broke settings, unable to reset BdBrowser

### ISSUE THREAD

**Issue by DrBrad22** [Strencher/BdBrowser#39]
I accidentally turned on 2 themes (DTM 16 and DTM 18) that are unable to work together and broke settings, making me unable to turn one of them off. I tried to uninstall and reinstall BdBrowser but it instantly applied the themes again, I even tried to use extension options but when I disabled BdBrowser rendering I can't access theme settings. I can't even find any way to clear the BdBrowser extension data. Can anyone help out?

**Comment by fowlis** [comment]
Assuming BdBrowser loads BdApi the same way the app does, try this script in console:
```
BdApi.Themes.getAll().forEach((theme) => BdApi.Themes.disable(theme));
```
Please also remember that Strencher has discontinued support for this, your issue should go to the working(?) fork.

**Comment by DrBrad22** [comment]
Update: I finally fixed the issue using tab and the arrow keys.
