### ISSUE TITLE
[Bug] Not loading at startup

### ISSUE THREAD

**Issue by KaKi87** [Strencher/BdBrowser#42]
Hi,

First of all, thank you for creating this project, BetterDiscord was the only reason why I was using the Electron app, but now, thanks to your extension, I enjoy its comfort in my already always open browser.

However, here's an issue : it doesn't load a startup (i.e. when the browser automatically reopens tabs at launch), but only after manually refreshing the tab once.

Thanks

**Comment by fowlis** [comment]
Strencher doesn't maintain BDBrowser anymore. [This fork](https://github.com/tsukasa/BdBrowser) is the most recently updated but you'll need to go to that repo for support if the issue still persists.

**Comment by KaKi87** [comment]
Hmm, I actually knew that, as that fork is the one I starred and installed after a [Useful Forks](https://useful-forks.github.io/) search.

I guess I got here instead of [there](https://github.com/tsukasa/BdBrowser/discussions/35) from a search engine result and didn't notice.

Linking to the fork from the README or at least archiving this one would be nice though.
