### ISSUE TITLE
clickToChat

### ISSUE THREAD

**Issue by lolpowerluke** [Strencher/BdBrowser#7]
clickToChat plugin doesnt work (it doesnt give any errors tho)
just the icon doesnt show up
I will check if the plugin still works on normal bd once I'm home, if it doesnt I'll just close this issue

**Comment by Serega007RU** [comment]
Everything works fine. Maybe you didn't install the 0PluginLibrary library (ZeresPluginLibrary)? This plugin requires this library to work

**Comment by lolpowerluke** [comment]
yeah, srry, completely forgot about this after I posted it
I tried it on bdBrowser I think, but it didnt work there, so I was gonna check if it works on normal discord, but forgot that
again, srry for the inconvienience and I'll close this issue now
